name: AdGuard Rules Merger

on:
  # 定时运行，每10分钟执行一次
  schedule:
    - cron: '*/10 * * * *'
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  merge-adguard-rules:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要写权限来提交更改
    
    steps:
      - name: 检出代码库
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 确保获取所有历史记录
          persist-credentials: false  # 禁用默认凭据，使用GitHub令牌
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 使用Python 3.10版本
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests  # 我们的脚本需要requests库
      
      - name: 运行AdGuard规则合并脚本
        run: |
          python scripts/adguard_rules_merger.py
      
      - name: 配置Git环境
        run: |
          # 配置Git用户信息
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
      
      - name: 添加规则文件
        run: |
          # 添加所有规则文件
          git add Black.txt White.txt scripts/colorful.txt
      
      - name: 提交更改
        run: |
          # 使用--allow-empty确保即使没有变更也创建提交
          git commit --allow-empty -m "Update AdGuard rules $(date +'%Y-%m-%d %H:%M:%S')"
          # 使用GitHub令牌进行认证和推送
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }} 2>&1
          # 捕获错误
          if [ $? -ne 0 ]; then
            echo "推送失败，尝试使用其他方式..."
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Actions自动提供的令牌
